
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import toast, { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'uMenu',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,

}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <RegisterModal />
        <Toaster/>
        <Navbar />
        <div>{children}</div> 
      </body>
    </html>
  )
}



