"use client";
import { SessionProvider } from "next-auth/react";
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import toast, { Toaster } from 'react-hot-toast';
import LoginModal from "./components/modals/LoginModal";
// import getCurrentUser from "./actions/getCurrentUser";


const inter = Inter({ subsets: ['latin'] })



// export const metadata = {
//   title: 'uMenu',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({
  children,

}: {
  children: React.ReactNode;
}) {
  // const currentUser = getCurrentUser();
  // console.log(currentUser);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <RegisterModal />
          <LoginModal />
          <Toaster />
          <Navbar />
          <div>{children}</div>
        </SessionProvider>
      </body>
    </html>
  )
}



